#!/bin/sh
# Fix scrolling issue in generated index.html
# This script fixes the HTML generated by Expo to ensure proper scrolling

set -e

echo "Fixing scrolling CSS in dist/index.html..."

if [ -f "dist/index.html" ]; then
  # Fix the expo-reset style to include html overflow and #root max-height
  # Original: <style id="expo-reset">#root,body,html{height:100%}body{overflow:hidden}#root{display:flex}</style>
  # Fixed:    <style id="expo-reset">#root,body,html{height:100%}html{overflow:hidden}body{overflow:hidden;display:flex}#root{display:flex;overflow:hidden;max-height:100vh}</style>
  
  sed -i.bak 's|<style id="expo-reset">#root,body,html{height:100%}body{overflow:hidden}#root{display:flex}</style>|<style id="expo-reset">#root,body,html{height:100%}html{overflow:hidden}body{overflow:hidden;display:flex}#root{display:flex;overflow:hidden;max-height:100vh}</style>|g' dist/index.html
  
  # Remove backup file if created (macOS sed creates .bak)
  [ -f "dist/index.html.bak" ] && rm dist/index.html.bak
  
  echo "✓ Fixed scrolling CSS in dist/index.html"
else
  echo "⚠ dist/index.html not found, skipping fix"
fi

echo "Scroll fix completed!"

